name: sfsymbols
description: A plugin to load SF Symbols from iOS.
repository: https://github.com/flutter/plugins/tree/master/packages/sfsymbols
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+sfsymbols%22
version: 0.1.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SFSymbolsPlugin
      macos:
        pluginClass: SFSymbolsPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
